export  { default as pokerLogo} from "./pokerLogo.svg"
export  { default as home} from "./home.svg"
export  { default as dollar} from "./dollar.svg"
export  { default as savings} from "./savings.svg"
export  { default as user} from "./user.svg"
export  { default as wptLogo} from "./wptLogo.svg"
export  { default as adduser} from "./adduser.svg"
export  { default as link} from "./link.svg"
export  { default as back} from "./back.svg"
export  { default as kkpokerlogo} from "./kkpokerlogo.svg"
export  { default as eyes} from "./eyes.svg"
export  { default as banner} from "./banner.png"
export  { default as pokerLifeCycle} from "./pokerLifeCycle.png"
export  { default as pokerBack} from "./pokerBack.png"
export  { default as form} from "./form.png"
export  { default as banner2} from "./banner2.png"
export  { default as signup} from "./signup.png"
export  { default as notification} from "./notification.png"
export  { default as rightArrow} from "./rightArrow.svg"
export  { default as blackLine} from "./blackLine.svg"
export  { default as whiteRightArrow} from "./whiteRightArrow.svg"


